# Generated by Django 3.2.6 on 2023-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=8)),
                ('amount_adult', models.DecimalField(decimal_places=5, help_text='Amount charged per adult. Only applicable if amountType = fixed_per_person (Per Person Per Night)', max_digits=8, null=True)),
                ('amount_child', models.DecimalField(decimal_places=5, help_text='Amount charged per children. Only applicable if amountType = fixed_per_person (Per Person Per Night)', max_digits=8, null=True)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('fixed_per_person', 'Fixed per person'), ('percentage_rate_based', 'Percentage rate based')], max_length=50)),
                ('available_for', models.JSONField()),
                ('inclusive_or_exclusive', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], max_length=50)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=8)),
                ('amount_adult', models.DecimalField(decimal_places=5, help_text='Amount charged per adult. Only applicable if amountType = fixed_per_person (Per Person Per Night)', max_digits=8, null=True)),
                ('amount_child', models.DecimalField(decimal_places=5, help_text='Amount charged per children. Only applicable if amountType = fixed_per_person (Per Person Per Night)', max_digits=8, null=True)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('fixed_per_person', 'Fixed per person'), ('percentage_rate_based', 'Percentage rate based')], max_length=50)),
                ('available_for', models.JSONField()),
                ('inclusive_or_exclusive', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive', 'Exclusive')], max_length=50)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
