# Generated by Django 3.2.6 on 2023-06-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(help_text='Room Type Name', max_length=255)),
                ('room_type_name_short', models.CharField(help_text='Room Type Short Name', max_length=255)),
                ('room_type_description', models.TextField(help_text='Room Type Description')),
                ('is_private', models.BooleanField(help_text='Whether room is private or shared')),
                ('max_guests', models.IntegerField(help_text='Max number of guests allowed in the room type')),
                ('adults_included', models.IntegerField(help_text='Number of adults included on the basic room rate')),
                ('children_included', models.IntegerField(help_text='Number of children included on the basic room rate')),
                ('room_type_features', models.ManyToManyField(help_text='List of features for the room type', to='app.HotelAmenity')),
            ],
            options={
                'verbose_name_plural': 'Room Type Details',
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='room_photos')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='room.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(help_text='Room Name', max_length=255)),
                ('dorm_room_name', models.CharField(help_text='Name of the dorm room. Used for the shared dorm beds that are organized into rooms within the same room type', max_length=255)),
                ('room_description', models.TextField(help_text='Room Description')),
                ('room_blocked', models.BooleanField(help_text='If room is blocked on calendar during the period selected. If no check-in/out dates are sent, it returns the status for the current day.')),
                ('room_type', models.ForeignKey(help_text='Room Type ID', on_delete=django.db.models.deletion.CASCADE, to='room.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
    ]
