# Generated by Django 3.2.6 on 2023-06-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='is_private',
            field=models.BooleanField(choices=[(False, 'Shared'), (True, 'Private')], help_text='Whether room is private or shared'),
        ),
    ]
