# Generated by Django 3.2.6 on 2023-06-10 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AppState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(help_text='Event object', max_length=255)),
                ('action', models.CharField(help_text='Event action', max_length=255)),
                ('endpoint_url', models.URLField(help_text='Endpoint URL', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the document. Will be used to describe the document in MFD.', max_length=255)),
                ('url', models.CharField(help_text='URL for the user to download the document.', max_length=255)),
                ('amount', models.FloatField(help_text='Value of the posted document.')),
                ('issue_date', models.DateTimeField(default=datetime.datetime.now, help_text='Datetime of document emission. If not sent, the current datetime will be assumed.')),
                ('house_account', models.ForeignKey(help_text='House Account identifier. It, or reservation_id, is necessary.', on_delete=django.db.models.deletion.CASCADE, to='app.houseaccount')),
                ('reservation', models.ForeignKey(help_text='Reservation identifier. It, or house_account_id, is necessary.', on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation')),
            ],
        ),
    ]
