# Generated by Django 3.2.6 on 2023-07-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_name', models.CharField(help_text='Enter the name of the rate interval', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of the rate interval')),
                ('end_date', models.DateField(help_text='End date of the rate interval')),
                ('min_length_of_stay', models.PositiveIntegerField(blank=True, help_text='Minimum length of stay for the interval', null=True)),
                ('max_length_of_stay', models.PositiveIntegerField(blank=True, help_text='Maximum length of stay for the interval', null=True)),
                ('closed_to_arrival', models.BooleanField(default=False, help_text='Specify if the interval is closed to arrival')),
                ('closed_to_departure', models.BooleanField(default=False, help_text='Specify if the interval is closed to departure')),
                ('additional_adult_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Additional fee for each additional adult', max_digits=8, null=True)),
                ('additional_child_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Additional fee for each additional child', max_digits=8, null=True)),
                ('enable_monday_price', models.BooleanField(default=True, help_text='Specify if Monday price is enabled')),
                ('enable_tuesday_price', models.BooleanField(default=True, help_text='Specify if Tuesday price is enabled')),
                ('enable_wednesday_price', models.BooleanField(default=True, help_text='Specify if Wednesday price is enabled')),
                ('enable_thursday_price', models.BooleanField(default=True, help_text='Specify if Thursday price is enabled')),
                ('enable_friday_price', models.BooleanField(default=True, help_text='Specify if Friday price is enabled')),
                ('enable_saturday_price', models.BooleanField(default=True, help_text='Specify if Saturday price is enabled')),
                ('sunday_price', models.DecimalField(decimal_places=2, help_text='Enter the price for Sunday', max_digits=8)),
                ('monday_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Monday', max_digits=8, null=True)),
                ('tuesday_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Tuesday', max_digits=8, null=True)),
                ('wednesday_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Wednesday', max_digits=8, null=True)),
                ('thursday_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Thursday', max_digits=8, null=True)),
                ('friday_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Friday', max_digits=8, null=True)),
                ('saturday_price', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Saturday', max_digits=8, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
