# Generated by Django 3.2.6 on 2023-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20230701_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateinterval',
            name='enable_sunday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='enable_friday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='enable_monday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='enable_saturday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='enable_thursday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='enable_tuesday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='enable_wednesday_price',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='friday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='monday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='saturday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='sunday_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='thursday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='tuesday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rateinterval',
            name='wednesday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
