# Generated by Django 3.2.6 on 2023-07-01 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomtype_is_private'),
        ('rate', '0003_auto_20230701_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateinterval',
            name='room_type',
            field=models.ForeignKey(default=1, help_text='Select the room type for the rate interval', on_delete=django.db.models.deletion.CASCADE, to='room.roomtype'),
            preserve_default=False,
        ),
    ]
