# Generated by Django 3.2.6 on 2023-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_rateinterval_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateinterval',
            name='sunday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
