from django.urls import path

from apps.settings import views

urlpatterns = [
    path('property-details/', views.settings_property_details_view, name='settings_property_details'),
    path('property-details/property-profile/', views.settings_property_details_property_profile_view,
         name='settings_property_details_property_profile'),
    path('property-details/property-amenities/', views.settings_property_details_property_amenities_view,
         name='settings_property_details_property_amenities'),
    path('property-details/room-types/', views.RoomTypeListView.as_view(), name='settings_room_type'),
    path('property-details/room-types/<int:pk>/edit/', views.settings_room_type_edit_view,
         name='settings_room_type_edit'),
    path('property-details/room-types/create/', views.settings_room_type_create_view, name='settings_room_type_create'),
    path('property-configuration/', views.settings_property_configuration_view,
         name='settings_property_configuration'),
    path('property-configuration/taxes-and-fees/', views.TaxesAndFeesListView.as_view(),
         name='settings_taxes_and_fees'),
    path('property-configuration/taxes-and-fees/<int:pk>/edit/', views.settings_taxes_and_fees_edit_view,
         name='settings_taxes_and_fees_edit'),
    path('property-configuration/taxes-and-fees/create/', views.settings_taxes_and_fees_create_view,
         name='settings_taxes_and_fees_create'),
    path('property-configuration/reservation-sources/', views.ReservationSourcesListView.as_view(),
         name='settings_reservation_sources'),
    path('property-configuration/reservation-sources/<int:pk>/edit/', views.settings_reservation_sources_edit_view,
         name='settings_reservation_sources_edit'),
    path('property-configuration/reservation-sources/create/', views.settings_reservation_sources_create_view,
         name='settings_reservation_sources_create'),
    path('property-configuration/item-categories/', views.ItemCategoryListView.as_view(),
         name='settings_item_category_index'),
    path('property-configuration/item-categories/<int:pk>/edit/', views.settings_item_category_edit_view,
         name='settings_item_category_edit'),
    path('property-configuration/item-categories/create/', views.settings_item_category_create_view,
         name='settings_item_category_create'),
    path('property-configuration/items/', views.ItemListView.as_view(), name='settings_item_index'),
    path('property-configuration/items/<int:pk>/edit/', views.settings_item_edit_view, name='settings_item_edit'),
    path('property-configuration/items/create/', views.settings_item_create_view, name='settings_item_create'),
    path('property-configuration/custom-fields/', views.CustomFieldListView.as_view(), name='settings_custom_field_index'),
    path('property-configuration/custom-fields/<int:pk>/edit/', views.settings_custom_field_edit_view, name='settings_custom_field_edit'),
    path('property-configuration/custom-fields/create/', views.settings_custom_field_create_view, name='settings_custom_field_create'),
    path('user-management/', views.settings_user_management_view, name='settings_user_management'),
    path('channel-distribution/', views.settings_channel_distribution_view,
         name='settings_channel_distribution'),
    path('email-configuration/', views.settings_email_configuration_view, name='settings_email_configuration'),
    path('email-configuration/email-templates/', views.EmailTemplateListView.as_view(),
         name='settings_email_configuration_email_templates'),
    path('email-configuration/email-templates/<int:pk>/edit/',
         views.settings_email_configuration_email_templates_edit_view,
         name='settings_email_configuration_email_templates_edit'),
    path('email-configuration/email-templates/create/', views.settings_email_configuration_email_templates_create,
         name='settings_email_configuration_email_templates_create'),
    path('email-configuration/email-schedules/', views.EmailScheduleListView.as_view(),
         name='settings_email_configuration_email_schedules'),
    path('email-configuration/email-schedules/<int:pk>/edit/',
         views.settings_email_configuration_email_schedules_edit_view,
         name='settings_email_configuration_email_schedules_edit'),
    path('email-configuration/email-schedules/create/', views.settings_email_configuration_email_schedules_create,
         name='settings_email_configuration_email_schedules_create'),
    path('system-notifications/', views.settings_system_notifications_view,
         name='settings_system_notifications'),
]
