# Generated by Django 3.2.6 on 2023-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(help_text='Property name', max_length=255)),
                ('property_image', models.ImageField(upload_to='property_images')),
                ('property_description', models.TextField(help_text='Property description')),
                ('property_primary_language', models.CharField(help_text='Property primary language', max_length=255)),
                ('property_phone', models.CharField(help_text='Property phone number', max_length=20)),
                ('property_email', models.EmailField(help_text='Property main email address', max_length=254)),
                ('property_address1', models.CharField(help_text='Property address line 1', max_length=255)),
                ('property_address2', models.CharField(help_text='Property address line 2', max_length=255)),
                ('property_city', models.CharField(help_text='Property city', max_length=255)),
                ('property_state', models.CharField(help_text='Property state', max_length=255)),
                ('property_zip', models.CharField(help_text='Property ZIP code', max_length=20)),
                ('property_country', models.CharField(help_text='Property country', max_length=255)),
                ('property_latitude', models.CharField(help_text='Property latitude', max_length=255)),
                ('property_longitude', models.CharField(help_text='Property longitude', max_length=255)),
                ('property_check_in_time', models.TimeField(help_text='Property check-in time')),
                ('property_check_out_time', models.TimeField(help_text='Property check-out time')),
                ('property_late_check_out_allowed', models.BooleanField(help_text='Property allows late check-out')),
                ('property_late_check_out_type', models.CharField(choices=[('value', 'Value'), ('percent', 'Percent')], help_text='If the property accepts late check-out, defines if the value is fixed, or a percentage of the daily rate', max_length=50)),
                ('property_late_check_out_value', models.FloatField(help_text='The fixed value, or percentage of the daily rate, to be charged on a late check-out')),
                ('property_terms_and_conditions', models.TextField(help_text='Text describing the terms and conditions to be displayed to guest')),
            ],
        ),
    ]
