# Generated by Django 3.2.6 on 2023-06-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('motel', 'Motel'), ('resort', 'Resort'), ('guesthouse', 'Guest House'), ('bed_breakfast', 'Bed and Breakfast'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('hostel', 'Hostel'), ('inn', 'Inn')], default='hotel', help_text='Property type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='property_website',
            field=models.URLField(blank=True, help_text='Property website URL'),
        ),
    ]
