# Generated by Django 3.2.6 on 2023-06-15 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20230615_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='property_images',
        ),
    ]
