# Generated by Django 3.2.6 on 2023-06-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
        ('settings', '0005_remove_hotel_property_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Guest status', max_length=255)),
                ('description', models.TextField(help_text='Guest status description')),
                ('guest', models.ManyToManyField(to='app.Guest')),
            ],
        ),
    ]
