# Generated by Django 3.2.6 on 2023-06-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
        ('settings', '0006_gueststatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststatus',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Guest status is active'),
        ),
        migrations.AlterField(
            model_name='gueststatus',
            name='guest',
            field=models.ManyToManyField(blank=True, to='app.Guest'),
        ),
    ]
