# Generated by Django 3.2.6 on 2023-06-16 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20230616_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gueststatus',
            old_name='guest',
            new_name='guests',
        ),
    ]
