# Generated by Django 3.2.6 on 2023-06-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomtype_is_private'),
        ('item', '0004_rename_itemcategories_itemcategory'),
        ('settings', '0008_rename_guest_gueststatus_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('charge_type', models.CharField(choices=[('reservation', 'Per Reservation'), ('night', 'Per Night'), ('room_bed', 'Per Room/Bed'), ('room_bed_night', 'Per Room/Bed Per Night'), ('guest', 'Per Guest'), ('guest_night', 'Per Guest Per Night'), ('quantity', 'Per Quantity')], max_length=20)),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True)),
                ('availability', models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('both', 'Both Arrival and Departure'), ('na', 'Not Applicable')], max_length=20)),
                ('post_transaction', models.CharField(choices=[('immediate', 'Immediately when receiving the reservation'), ('checkin', 'When checking-in the reservation'), ('daily', 'Post Add-On daily')], max_length=20)),
                ('keep_posted_on_cancellation', models.BooleanField(default=True)),
                ('calculate_revenue', models.CharField(choices=[('proportional', 'Adjust its price proportionally to the other package inclusions'), ('full_price', 'Calculate based on the full price')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='add_ons')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_overlap', models.PositiveIntegerField()),
                ('max_overlap', models.PositiveIntegerField()),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.addon')),
                ('room_types', models.ManyToManyField(to='room.RoomType')),
            ],
        ),
        migrations.CreateModel(
            name='AddOnPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_of_week', models.CharField(max_length=20)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.addoninterval')),
            ],
        ),
    ]
