# Generated by Django 3.2.6 on 2023-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_addon_addoninterval_addonprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='addoninterval',
            name='friday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addoninterval',
            name='monday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addoninterval',
            name='saturday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addoninterval',
            name='sunday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addoninterval',
            name='thursday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addoninterval',
            name='tuesday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='addoninterval',
            name='wednesday_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='AddOnPrice',
        ),
    ]
