# Generated by Django 3.2.6 on 2023-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomtype_is_private'),
        ('settings', '0010_auto_20230617_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='availability',
            field=models.CharField(choices=[('arrival', 'Arrival'), ('departure', 'Departure'), ('both', 'Both Arrival and Departure'), ('na', 'Not Applicable')], help_text='Select when the add-on will be available', max_length=20),
        ),
        migrations.AlterField(
            model_name='addon',
            name='calculate_revenue',
            field=models.CharField(choices=[('proportional', 'Adjust its price proportionally to the other package inclusions'), ('full_price', 'Calculate based on the full price')], help_text='Choose how add-on values will be calculated for revenue allocation', max_length=20),
        ),
        migrations.AlterField(
            model_name='addon',
            name='charge_type',
            field=models.CharField(choices=[('reservation', 'Per Reservation'), ('night', 'Per Night'), ('room_bed', 'Per Room/Bed'), ('room_bed_night', 'Per Room/Bed Per Night'), ('guest', 'Per Guest'), ('guest_night', 'Per Guest Per Night'), ('quantity', 'Per Quantity')], help_text='Select the type of charge', max_length=20),
        ),
        migrations.AlterField(
            model_name='addon',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (recommended: 150px x 75px)', null=True, upload_to='add_ons'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='keep_posted_on_cancellation',
            field=models.BooleanField(default=True, help_text='Choose whether to keep or void the transaction on cancellation/no show'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(help_text='This will be displayed on the booking engine mybookings', max_length=255),
        ),
        migrations.AlterField(
            model_name='addon',
            name='post_transaction',
            field=models.CharField(choices=[('immediate', 'Immediately when receiving the reservation'), ('checkin', 'When checking-in the reservation'), ('daily', 'Post Add-On daily')], help_text='Select when the transaction should be posted', max_length=20),
        ),
        migrations.AlterField(
            model_name='addon',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='Internal transaction code (optional)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='end_date',
            field=models.DateField(help_text='Set the end date of the interval'),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='friday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Friday', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='max_overlap',
            field=models.PositiveIntegerField(help_text='Set the maximum number of consecutive reservation days the add-on must be available'),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='min_overlap',
            field=models.PositiveIntegerField(help_text='Set the minimum number of consecutive reservation days the add-on must be available'),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='monday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Monday', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='name',
            field=models.CharField(blank=True, help_text='Interval name (internal only)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='room_types',
            field=models.ManyToManyField(help_text='Select the room types for which this add-on will be available', to='room.RoomType'),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='saturday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Saturday', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='start_date',
            field=models.DateField(help_text='Set the start date of the interval'),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='sunday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Sunday', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='thursday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Thursday', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='tuesday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Tuesday', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='addoninterval',
            name='wednesday_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the price for Wednesday', max_digits=10, null=True),
        ),
    ]
