# Generated by Django 3.2.6 on 2023-06-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_auto_20230617_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addoninterval',
            name='name',
            field=models.CharField(default='a', help_text='Interval name (internal only)', max_length=255),
            preserve_default=False,
        ),
    ]
