# Generated by Django 3.2.6 on 2023-06-17 20:42

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_automationpreferences_generalsystemsettings_miscellaneouspreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_language', models.CharField(choices=[('en', 'English'), ('bs', 'Bosnian')], help_text='Select the default language for your property. New user accounts will have this language.', max_length=2)),
                ('application_date_format', models.CharField(choices=[('Y-m-d', 'YYYY-MM-DD'), ('m/d/Y', 'MM/DD/YYYY')], help_text='Select the format in which the date is shown on HotelHeroic PMS.', max_length=10)),
                ('application_time_format', models.CharField(choices=[('H:i', '24-hour format'), ('h:i A', '12-hour format')], help_text='Select the format in which the time is shown on HotelHeroic PMS.', max_length=6)),
                ('property_time_zone', timezone_field.fields.TimeZoneField(help_text='The time zone of your property.')),
                ('application_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro')], help_text='The main currency on Cloudbeds PMS.', max_length=50)),
                ('allow_additional_bookings', models.BooleanField(default=False, help_text='Enabling this will open availability when your property is at no less than 100% occupancy.')),
                ('auto_change_no_show', models.BooleanField(default=True, help_text='When a guest does not show up the next day after the arrival date by 2:05 AM, the system will automatically change the status of the reservation to "No Show".')),
                ('auto_checkout_date_extension', models.BooleanField(default=True, help_text='When a guest does not manually check out until 2:05 AM the next day, the system will automatically extend the reservation date.')),
                ('auto_assign_reservations', models.BooleanField(default=False, help_text='If enabled, all new reservations will be auto-assigned to the first available accommodation within that room type.')),
                ('use_default_country_for_guest', models.BooleanField(default=False, help_text="When turned on, the country field in guest details will be pre-filled with your property's country.")),
                ('allow_same_day_bookings', models.BooleanField(default=False, help_text='If enabled, guests will be allowed to book same-day arrivals.')),
                ('same_day_bookings_until', models.TimeField(blank=True, help_text='Specify until what time the guest is allowed to book for the same-day arrival.', null=True)),
                ('show_estimated_arrival_time', models.BooleanField(default=False, help_text="Gives you the option to fill in the guest's estimated arrival time when creating direct reservations.")),
                ('show_checkouts_in_departure_list', models.BooleanField(default=True, help_text="If enabled, the property can see guests who have already checked out in their dashboard's Departure List.")),
                ('enable_gdpr_compliance', models.BooleanField(default=False, help_text='If enabled, tools to comply with GDPR such as Guest Data Extraction, Anonymization, and Marketing Opt-In will be available to your property.')),
                ('customer_name_format', models.CharField(choices=[('SURNAME_NAME', 'Surname Name'), ('NAME_SURNAME', 'Name Surname')], help_text='Specifies how the customer name is displayed in the calendar.', max_length=50)),
                ('enable_payment_allocation', models.BooleanField(default=False, help_text='Enabling payment allocation allows users to specify exactly which charge a payment is for.')),
                ('breakfast_included_channel_distribution', models.BooleanField(default=False, help_text='Tells channels (OTAs) if breakfast pricing is included in your nightly rates.')),
                ('require_full_payment_prior_to_check_in', models.BooleanField(default=False, help_text='If enabled, reservations with a remaining balance cannot be checked-in until full payment is collected.')),
            ],
        ),
        migrations.DeleteModel(
            name='AutomationPreferences',
        ),
        migrations.DeleteModel(
            name='GeneralSystemSettings',
        ),
        migrations.DeleteModel(
            name='MiscellaneousPreferences',
        ),
    ]
