# Generated by Django 3.2.6 on 2023-06-18 09:43

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20230617_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount'), ('first_day_price', 'First Day Price'), ('no_deposit', 'Do not collect deposit')], default='percentage', help_text='Select the type of deposit for your guests.', max_length=15)),
                ('deposit_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Specify the required deposit percentage (%).', max_digits=5, null=True)),
                ('deposit_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Specify the fixed amount that will be charged per accommodation per night.', max_digits=10, null=True)),
                ('include_taxes_fees', models.BooleanField(default=False, help_text='Specify whether taxes and fees will be included as part of the deposit.')),
                ('capture_credit_card', models.BooleanField(default=False, help_text='Select if you would like to capture the guest credit card details to keep on file.')),
            ],
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', help_text='The main currency on Cloudbeds PMS.', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_date_format',
            field=models.CharField(choices=[('d/m/Y', 'DD/MM/YYYY'), ('Y-m-d', 'YYYY-MM-DD'), ('m/d/Y', 'MM/DD/YYYY')], default='d/m/Y', help_text='Select the format in which the date is shown on HotelHeroic PMS.', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_language',
            field=models.CharField(choices=[('en', 'English'), ('bs', 'Bosnian')], default='en', help_text='Select the default language for your property. New user accounts will have this language.', max_length=2),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='application_time_format',
            field=models.CharField(choices=[('H:i', '24-hour format'), ('h:i A', '12-hour format')], default='H:i', help_text='Select the format in which the time is shown on HotelHeroic PMS.', max_length=6),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='customer_name_format',
            field=models.CharField(choices=[('SURNAME_NAME', 'Surname Name'), ('NAME_SURNAME', 'Name Surname')], default='SURNAME_NAME', help_text='Specifies how the customer name is displayed in the calendar.', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='property_time_zone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Sarajevo', help_text='The time zone of your property.'),
        ),
    ]
