# Generated by Django 3.2.6 on 2023-06-18 13:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Enter your terms and conditions. Apply format if needed.'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bs', 'Bosnian')], default='en', help_text='Choose the language for your terms and conditions.', max_length=2),
        ),
    ]
