# Generated by Django 3.2.6 on 2023-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_arrivalanddeparture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_confirmation_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('confirmation_pending', 'Confirmation Pending')], default='confirmed', help_text='Select your preferred default confirmation status for new reservations.', max_length=20)),
            ],
        ),
    ]
