# Generated by Django 3.2.6 on 2023-06-18 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0020_invoicedetails_invoicesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_reservation', 'New Reservation Received'), ('reservation_cancelled', 'Reservation Cancelled'), ('reservation_modified', 'Reservation Modified (modification from OTA)'), ('reservation_unmapped', 'Modification to Reservation with Unmapped Rooms'), ('no_show_reported', 'No Shows Auto-Reported to Booking.com'), ('payment_success', 'Payment processed successfully'), ('payment_failure', 'Unable to process payment'), ('chargeback', 'Chargeback Notifications / Resolutions'), ('drawer_closure', 'Drawer Closure Summary Notifications')], help_text='Select the type of system notification.', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recipients', models.ManyToManyField(help_text='Select the recipients for this notification type.', related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
