# Generated by Django 3.2.6 on 2023-06-18 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_auto_20230618_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='hotel',
            field=models.ForeignKey(default=1, help_text='Select the hotel for this notification type.', on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to='settings.hotel'),
            preserve_default=False,
        ),
    ]
