# Generated by Django 3.2.6 on 2023-06-18 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0023_systemnotification_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='recipients',
            field=models.ManyToManyField(blank=True, help_text='Select the recipients for this notification type.', related_name='system_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
