# Generated by Django 3.2.6 on 2023-06-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_alter_systemnotification_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover')], max_length=100)),
                ('accepted_for_direct_reservations', models.BooleanField(default=False)),
                ('accepted_for_mybookings', models.BooleanField(default=False)),
            ],
        ),
    ]
