# Generated by Django 3.2.6 on 2023-06-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover')], max_length=50, unique=True),
        ),
    ]
