# Generated by Django 3.2.6 on 2023-06-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_alter_creditcard_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Switch to activate or deactivate Bank Transfer as a payment option for your property.', verbose_name='Activate/Deactivate')),
                ('direct_reservations_allowed', models.BooleanField(default=False, help_text='Allow Bank Transfer as a payment option for direct/dashboard reservations.', verbose_name='Direct / Dashboard Reservations')),
                ('booking_engine_allowed', models.BooleanField(default=False, help_text='Allow Bank Transfer as a payment option for bookings made through the Mybookings Booking Engine.', verbose_name='Mybookings Booking Engine')),
                ('bank_name', models.CharField(help_text='Enter the name of your bank.', max_length=100, verbose_name='Bank Name')),
                ('bank_address', models.TextField(help_text='Enter the address of your bank.', verbose_name='Bank Address')),
                ('property_address', models.TextField(help_text='Enter the address of your property where bank transfer details should be listed.', verbose_name='Property Address')),
                ('bank_account_details', models.TextField(help_text='Enter the details of your bank account.', verbose_name='Bank Account Details')),
            ],
        ),
    ]
