# Generated by Django 3.2.6 on 2023-06-20 21:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_banktransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransfer',
            name='bank_account_details',
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='instructions',
            field=ckeditor.fields.RichTextField(default='', help_text='Instructions for completing the transfer.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='active',
            field=models.BooleanField(default=False, help_text='Switch to activate or deactivate Bank Transfer as a payment option for your property.'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='bank_address',
            field=models.TextField(help_text='Enter the address of your bank.'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='bank_name',
            field=models.CharField(help_text='Enter the name of your bank.', max_length=100),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='booking_engine_allowed',
            field=models.BooleanField(default=False, help_text='Allow Bank Transfer as a payment option for bookings made through the Mybookings Booking Engine.'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='direct_reservations_allowed',
            field=models.BooleanField(default=False, help_text='Allow Bank Transfer as a payment option for direct/dashboard reservations.'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='property_address',
            field=models.TextField(help_text='Enter the address of your property where bank transfer details should be listed.'),
        ),
    ]
