# Generated by Django 3.2.6 on 2023-06-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_auto_20230620_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Switch to activate or deactivate PayPal as a payment option for your guests.')),
                ('email_address', models.EmailField(help_text='Enter the email address associated with your PayPal account.', max_length=254, verbose_name='Email Address')),
                ('identity_token', models.CharField(blank=True, help_text='Enter the PayPal Identity Token, if necessary.', max_length=100)),
                ('first_name', models.CharField(help_text='Enter the first name of the person the PayPal account is registered under.', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the last name of the person the PayPal account is registered under.', max_length=100, verbose_name='Last Name')),
            ],
        ),
    ]
