# Generated by Django 3.2.6 on 2023-06-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_paypal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Enter the label/name for your custom payment method.', max_length=100, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Switch to activate or deactivate the custom payment method.')),
            ],
        ),
    ]
