# Generated by Django 3.2.6 on 2023-06-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_custompaymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('full_charge', 'Full Charge'), ('partial_charge', 'Partial Charge'), ('no_charge', 'No Charge')], max_length=20)),
                ('charge_type', models.CharField(choices=[('full_deposit', 'Full Deposit'), ('full_stay', 'Full Stay')], max_length=20)),
                ('days_before_arrival', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Cancellation Policies',
            },
        ),
        migrations.CreateModel(
            name='GeneralCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('standardized', 'Use standardized cancellation policy'), ('custom', 'Enter my own custom text policy')], default='standardized', help_text='Select the cancellation policy type.', max_length=20)),
                ('custom_content', models.TextField(blank=True, help_text='Enter your own custom text cancellation policy.', null=True)),
            ],
            options={
                'verbose_name_plural': 'General Cancellation Policies',
            },
        ),
    ]
