# Generated by Django 3.2.6 on 2023-07-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomtype_is_private'),
        ('settings', '0031_cancellationpolicy_generalcancellationpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_display_option', models.CharField(choices=[('lowest_price', 'Show Lowest Sales Price'), ('accommodation_total', 'Show Accommodation Total Price for Stay')], default='accommodation_total', help_text='Select the option for displaying prices in the gallery design.', max_length=20)),
                ('accommodation_booking_option', models.CharField(choices=[('specific', 'Allow guests to book specific accommodations'), ('general', 'General booking for the selected room type')], default='general', help_text='Select the option for accommodation booking.', max_length=20)),
                ('opt_in_to_marketing', models.BooleanField(default=False, help_text='Allow guests to opt-in to marketing emails during the booking process.')),
                ('marketing_content', models.TextField(blank=True, help_text='Additional content explaining the marketing emails.', null=True)),
                ('ask_postal_address', models.BooleanField(default=False, help_text='Ask for a postal address.')),
                ('ask_nationality', models.BooleanField(default=False, help_text='Ask for nationality.')),
                ('ask_gender', models.BooleanField(default=False, help_text='Ask for gender.')),
                ('ask_personal_tax_id', models.BooleanField(default=False, help_text='Ask for personal tax ID number.')),
                ('ask_company_name', models.BooleanField(default=False, help_text='Ask for company name.')),
                ('ask_company_tax_id', models.BooleanField(default=False, help_text='Ask for company tax ID name.')),
                ('require_telephone_number', models.BooleanField(default=False, help_text='Require telephone number to book.')),
                ('ask_estimated_arrival_time', models.BooleanField(default=False, help_text='Ask for estimated arrival time during booking.')),
                ('require_terms_conditions', models.BooleanField(default=False, help_text='Require acceptance of terms and conditions.')),
                ('confirmation_email', models.BooleanField(default=False, help_text='Send an automatic confirmation email to the guest.')),
                ('redirect_url', models.URLField(blank=True, help_text='URL to redirect guests after completing the booking.', null=True)),
                ('allotment_enabled', models.BooleanField(default=False, help_text='Enable allotment to limit the number of rooms available.')),
                ('quantity_to_sell', models.PositiveIntegerField(default=0, help_text='Number of rooms to sell when allotment is enabled.')),
                ('limit_same_type_accommodations', models.PositiveIntegerField(default=0, help_text='Limit the number of rooms bookable in one reservation.')),
                ('ask_cvv_code', models.BooleanField(default=False, help_text='Ask for CVV code for credit card payments.')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Booking Engine Settings',
            },
        ),
    ]
