# Generated by Django 3.2.6 on 2023-07-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roomtype_is_private'),
        ('settings', '0032_bookingenginesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingenginesettings',
            name='room_type',
        ),
        migrations.AddField(
            model_name='bookingenginesettings',
            name='room_type',
            field=models.ManyToManyField(to='room.RoomType'),
        ),
    ]
