# Generated by Django 3.2.6 on 2023-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0033_auto_20230701_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingenginesettings',
            name='hide_map',
            field=models.BooleanField(default=False, help_text='Hide the map on the booking page.'),
        ),
    ]
