# Generated by Django 3.2.6 on 2023-07-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_bookingenginesettings_hide_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingenginesettings',
            name='opt_in_option',
            field=models.CharField(blank=True, help_text='Text explaining the opt-in marketing option.', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingenginesettings',
            name='opt_out_option',
            field=models.CharField(blank=True, help_text='Text explaining the opt-out marketing option.', max_length=100),
        ),
    ]
