# Generated by Django 3.2.6 on 2023-07-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_auto_20230701_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingenginesettings',
            name='allotment_enabled',
        ),
        migrations.RemoveField(
            model_name='bookingenginesettings',
            name='quantity_to_sell',
        ),
        migrations.AddField(
            model_name='bookingenginesettings',
            name='redirect_on_confirmation',
            field=models.BooleanField(default=False, help_text='Redirect guests to a custom URL after completing the booking.'),
        ),
    ]
