# Generated by Django 3.2.6 on 2023-07-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_auto_20230701_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingenginesettings',
            old_name='room_type',
            new_name='room_types',
        ),
    ]
