# Generated by Django 3.2.6 on 2023-07-01 21:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_rename_room_type_bookingenginesettings_room_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEngineCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('header_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('room_arrow_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('search_button_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('general_button_color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None)),
                ('custom_meta_tags', models.TextField(blank=True, help_text='Custom meta tags for the header', null=True)),
                ('custom_meta_tags_confirmation', models.TextField(blank=True, help_text='Custom meta tags for the confirmation page', null=True)),
                ('javascript_code_confirmation', models.TextField(blank=True, help_text='JavaScript code for the confirmation page', null=True)),
                ('display_property_photos', models.BooleanField(default=True, help_text='Display property photos on the booking page')),
                ('logo', models.ImageField(blank=True, help_text='Property logo', null=True, upload_to='booking_engine/logos/')),
                ('custom_header', models.TextField(blank=True, help_text='Custom header for the booking page', null=True)),
                ('custom_footer', models.TextField(blank=True, help_text='Custom footer for the booking page', null=True)),
                ('no_availability_text', models.TextField(blank=True, help_text='Custom text when there is no availability for the searched dates', null=True)),
            ],
            options={
                'verbose_name_plural': 'Booking Engine Customizations',
            },
        ),
    ]
