# Generated by Django 3.2.6 on 2023-07-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0038_bookingenginecustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingenginecustomization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Property logo', null=True, upload_to='logos'),
        ),
    ]
