# Generated by Django 3.2.6 on 2023-06-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
        ('room', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housekeepingstatus',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='housekeepingassignment',
            name='housekeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.housekeeper'),
        ),
        migrations.AddField(
            model_name='housekeepingassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
        migrations.AddField(
            model_name='hotelamenity',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='settings.hotel'),
        ),
        migrations.AddField(
            model_name='guestnote',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guest'),
        ),
    ]
