# Generated by Django 3.2.6 on 2023-06-10 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_initial'),
        ('reservation', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
        migrations.AddField(
            model_name='emailschedule',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emailtemplate'),
        ),
        migrations.AddField(
            model_name='currencysettingsrate',
            name='currency_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='app.currencysettings'),
        ),
        migrations.AddField(
            model_name='currency',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.hotel'),
        ),
        migrations.AddField(
            model_name='adjustment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
