# Generated by Django 3.2.6 on 2023-06-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelamenity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether amenity is active or not'),
        ),
    ]
