# Generated by Django 3.2.6 on 2023-06-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxesandfees', '0002_auto_20230614_1808'),
        ('item', '0002_auto_20230614_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='taxes_and_fees',
            field=models.ManyToManyField(blank=True, help_text='Details of the fees applicable', related_name='items', to='taxesandfees.TaxAndFee'),
        ),
    ]
