# Generated by Django 3.2.6 on 2023-06-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source',
            new_name='ReservationSource',
        ),
    ]
